apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
spec:
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |
          Параметры экземпляра `linstor`.
