apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: linstors.deckhouse.io
  labels:
    heritage: deckhouse
    module: linstor
spec:
  group: deckhouse.io
  scope: Cluster
  names:
    plural: linstors
    singular: linstor
    kind: Linstor
  preserveUnknownFields: false
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: |
          Parameters of the `linstor` instance.
        properties:
          spec:
            type: object
            properties:
          metadata:
            type: object
            properties:
              name:
                type: string
                enum: ["linstor"]
